spring:
  jpa:
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/desafiosessaovotacaopautaapi #${JDBC_DATABASE_URL}
    username: desafiosessaovotacaopautaapi #${JDBC_DATABASE_USERNAME}
    password: desafiosessaovotacaopautaapi #${JDBC_DATABASE_PASSWORD}
