spring:
  jpa:
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/desafiosessaovotacaopautaapi
    username: desafiosessaovotacaopautaapi
    password: desafiosessaovotacaopautaapi
