spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/desafiosessaovotacaopautaapi
    username: desafiosessaovotacaopautaapi
    password: desafiosessaovotacaopautaapi
