version: "3"
services:
  api:
    container_name: desafio-sessao-votacao-pauta-api
    image: desafio-sessao-votacao-pauta-api
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
    ports:
      - 9091:8080
    links:
      - api-database-postgresql
  api-database-postgresql:
    extends:
      file: postgresql.yml
      service: api-database-postgresql
