version: "3"
services:
  api-database-postgresql:
    container_name: api-database-postgresql
    image: postgres:13.1
    environment:
      - POSTGRES_USER=desafiosessaovotacaopautaapi
      - POSTGRES_PASSWORD=desafiosessaovotacaopautaapi
    ports:
      - 5432:5432
    volumes:
      - api-database-postgresql:/var/lib/postgresql/data/
volumes:
  api-database-postgresql:
    driver: local
