version: "3"
services:
  api-database-postgresql:
    container_name: api-database-postgresql
    image: postgres:13.1
    environment:
      - POSTGRES_USER=desafiosessaovotacaopautaapi
      - POSTGRES_PASSWORD=!@DesafioSessaoVotacaoPautaApi
    ports:
      - 55432:5432
    volumes:
      - data-volume:/var/lib/postgresql/data/
volumes:
  data-volume:
    driver: local
